#script for inputting data and tuples into the database

# Vendor

insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (1, 'Hugo', 'Debow', '62', 'Velký Újezd', '1617');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (2, 'Guglielmo', 'Croucher', '91625', 'Yangxi', '526');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (3, 'Carolus', 'Sucre', '44796', 'Seremban', '2763');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (4, 'Dieter', 'Stutter', '8', 'Selaparang Timur', '5');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (5, 'Shelby', 'Yeldon', '13027', 'Kostinbrod', '142');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (6, 'Ignace', 'Hudghton', '07', 'Thành Phố Phủ Lý', '2064');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (7, 'Hedda', 'Hebner', '26', 'Palos', '5697');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (8, 'Lanna', 'Barkshire', '4', 'Baiju', '776');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (9, 'Brig', 'Siddaley', '61553', 'Bizana', '2');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (10, 'Gillie', 'Nichol', '955', 'Nema', '81378');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (11, 'Joby', 'Bierton', '5421', 'Xinchang', '664');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (12, 'Denny', 'Madgwich', '948', 'Lanchyn', '201');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (13, 'Gonzales', 'Gatward', '06', 'Zouila', '3303');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (14, 'Wendall', 'Islep', '1', 'Songlong', '4413');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (15, 'Lida', 'Linacre', '8', 'Listvyanka', '8');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (16, 'Winthrop', 'Gauld', '4', 'Waalwijk', '02752');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (17, 'Lennard', 'Forster', '15', 'Willemstad', '6');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (18, 'Paloma', 'Kiddye', '886', 'Werasari', '104');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (19, 'Starla', 'Hatz', '67', 'Alvaro Obregon', '54743');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (20, 'Grover', 'Brunnstein', '19', 'Houston', '57025');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (21, 'Denys', 'Daffern', '7242', 'Birowo', '5');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (22, 'Helaine', 'Nance', '9', 'Ponta da Garça', '3');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (23, 'Tadio', 'Fontanet', '3909', 'Zhangqing', '28');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (24, 'Sofie', 'Upston', '909', 'Jāwā', '6');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (25, 'Valdemar', 'Havercroft', '02', 'Quintães', '33');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (26, 'Sofie', 'Bezzant', '4880', 'Magitang', '99');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (27, 'Alfonse', 'Maffey', '320', 'Nikol’sk', '16679');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (28, 'Raimondo', 'Blader', '46058', 'Berlin', '90');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (29, 'Kleon', 'Droogan', '9', 'Czarna', '0277');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (30, 'El', 'Kuschke', '651', 'Rakhmanovo', '10782');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (31, 'Angelika', 'Mustoe', '16628', 'Medalem', '2733');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (32, 'Con', 'Moulden', '7', 'Piedra Blanca', '70');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (33, 'Carilyn', 'McCowen', '9', 'Jendouba', '31');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (34, 'Perry', 'Clayborn', '1322', 'Tyler', '2843');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (35, 'Ileana', 'Vasentsov', '47660', 'Ngembo', '9600');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (36, 'Wiley', 'Braikenridge', '240', 'Vohipaho', '21');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (37, 'Isa', 'Aluard', '769', 'Cimanggu Wetan', '14');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (38, 'Reeba', 'Kielty', '195', 'Tirmiz', '45');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (39, 'Chance', 'Rice', '2', 'Colos', '974');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (40, 'Adriano', 'Battin', '0132', 'Timbó', '173');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (41, 'Georgeta', 'Fripps', '47345', 'Jhang Sadr', '3826');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (42, 'Leicester', 'Huban', '826', 'Arjona', '026');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (43, 'Kial', 'Proswell', '32', 'Ciénega', '1');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (44, 'Stillman', 'Rutherford', '3', 'An Châu', '4');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (45, 'Curtice', 'Kerins', '2951', 'Guadalupe Victoria', '2');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (46, 'Everett', 'Kasperski', '710', 'Lākshām', '01');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (47, 'Malia', 'Bythell', '26548', 'Желино', '0068');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (48, 'Jephthah', 'Cousens', '0223', 'Sihanoukville', '85895');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (49, 'Alaine', 'Hardwin', '2', 'Bergerac', '436');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (50, 'Layney', 'Harrowing', '57385', 'Zhangjiahe', '7721');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (51, 'Bayard', 'Tym', '242', 'Joaquín V. González', '9');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (52, 'Cheryl', 'Hellis', '63223', 'Galižana', '8417');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (53, 'Kinsley', 'Cariss', '1', 'Barili', '9');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (54, 'Chevalier', 'Shilling', '616', 'Wuluquele', '4694');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (55, 'Brander', 'Pendreigh', '8', 'Gaoshi', '88');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (56, 'Leonelle', 'Lazenby', '5005', 'Donskoy', '4');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (57, 'Anjela', 'Rich', '88873', 'Owo', '7395');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (58, 'Magdalen', 'Komorowski', '87877', 'Haveluloto', '4');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (59, 'Cloris', 'Wellbeloved', '9669', 'Lhoknga', '750');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (60, 'Elisa', 'Allibone', '9415', 'Fengjiang', '94');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (61, 'Aksel', 'Bartalini', '9', 'Nangerang', '4809');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (62, 'Lani', 'Sivill', '983', 'Wengang', '92317');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (63, 'Kathi', 'Gaitskell', '363', 'Xingyi', '6');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (64, 'Ludvig', 'Gheeorghie', '2', 'Mombetsu', '631');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (65, 'Frankie', 'Bruford', '273', 'Kaoshan', '4');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (66, 'Brigida', 'Robrow', '24841', 'Phong Điền', '0');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (67, 'Eddi', 'Waszczyk', '727', 'Pasirpanjang', '54');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (68, 'Giordano', 'Pash', '233', 'Obeliai', '531');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (69, 'Wynnie', 'Lanfranchi', '4', 'Ekibastuz', '52430');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (70, 'Elyn', 'Probyn', '021', 'Chocos', '21195');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (71, 'Anabal', 'Wakes', '65', 'Paris La Défense', '974');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (72, 'Geralda', 'Karlsson', '8780', 'Caeté', '4230');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (73, 'Merridie', 'Igo', '54503', 'Nazareth', '05308');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (74, 'Hymie', 'Atkinson', '90674', 'Noginsk-9', '69771');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (75, 'Harvey', 'Verrick', '26813', 'Hexia', '91');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (76, 'Grata', 'Dailly', '77694', 'Wonopringgo', '27955');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (77, 'Brigg', 'Formigli', '54', 'Hullo', '0238');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (78, 'Ruggiero', 'Klos', '02', 'Dolgoprudnyy', '09581');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (79, 'Belvia', 'Baptist', '4', 'Makur', '9003');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (80, 'Maddy', 'Doeg', '35632', 'Anggana', '7');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (81, 'Sharia', 'Hymans', '54', 'Gouveia', '5399');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (82, 'Desi', 'Christiensen', '04', 'Oslo', '737');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (83, 'Con', 'Onions', '12', 'Lokolande', '345');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (84, 'Massimiliano', 'Gueste', '34', 'Oslo', '37');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (85, 'Belvia', 'Linzee', '266', 'Krajan', '360');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (86, 'Anissa', 'De La Salle', '6', 'Jayune', '486');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (87, 'Kane', 'Genty', '6', 'Dongkeng', '93327');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (88, 'Kahaleel', 'Osment', '583', 'Ōdachō-ōda', '02698');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (89, 'Frederick', 'Jeavons', '78113', 'Le Mans', '0743');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (90, 'Ambrosius', 'Stoodale', '774', 'Tomé', '1');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (91, 'Dolly', 'Spykins', '57', 'Yepocapa', '3');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (92, 'Dave', 'Flipek', '69245', 'Lat Yao', '9');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (93, 'Murdock', 'Jodlkowski', '8', 'Gryaznovskoye', '8');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (94, 'Wallie', 'Ervin', '95661', 'Shengao', '47656');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (95, 'Grazia', 'Iorillo', '0', 'Taketoyo', '9');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (96, 'Clari', 'McBrady', '2670', 'San Juan de Dios', '1912');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (97, 'Lorenza', 'Herculeson', '35', 'Maliana', '6198');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (98, 'Caitlin', 'Kittel', '57319', 'Valdemarsvik', '4393');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (99, 'Karissa', 'Alsop', '97', 'Dankalwa', '26250');
insert into Vendor (Vendor_ID, first_name, last_name, Plot_number, City, Pincode) values (100, 'Hollyanne', 'Papen', '6', 'San Antonio', '86558');
# Rows: