#script for inputting data and tuples into the database
use online_shopping;

#Customer
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (1, 'Shurlock', 'Sadgrove', '3978', 'Eastlawn', 'Na Muen', 872979, 'ssadgrove0@sitemeter.com', 'LJc5AVRCdR');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (2, 'Allin', 'Millward', '77919', 'Gerald', 'Erie', 469017, 'amillward1@techcrunch.com', 'Cg8hpuQk2zK');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (3, 'Algernon', 'Clemoes', '2140', 'Menomonie', 'Mulan', 739352, 'aclemoes2@stumbleupon.com', 'teh1Xj');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (4, 'Mariele', 'Eady', '3', 'Montana', 'Riyadh', 674094, 'meady3@topsy.com', 'n3pq9BM');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (5, 'Forrest', 'Silcock', '5', 'Barnett', 'Ponikiew', 288549, 'fsilcock4@1688.com', 'wGmQ0qd');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (6, 'Cherilyn', 'Stubbs', '1', 'Oriole', 'Talacogon', 326232, 'cstubbs5@abc.net.au', 'K4B2VeOX');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (7, 'Pegeen', 'Belfelt', '5932', 'Kenwood', 'Toritama', 109048, 'pbelfelt6@npr.org', 'j2XLLuhoZ3O');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (8, 'Niki', 'Shaddock', '2102', 'Linden', 'Al Metlaoui', 449833, 'nshaddock7@cloudflare.com', '8z4SFkBS3lcb');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (9, 'Agneta', 'Shawcross', '7', 'Meadow Valley', 'Štítina', 607446, 'ashawcross8@1und1.de', 'c5hGjO5lHyK');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (10, 'Murry', 'Shepstone', '3359', 'Esker', 'Luoshanchuan', 791387, 'mshepstone9@prweb.com', '1roHumY');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (11, 'Shawnee', 'Mertin', '246', 'Sloan', 'Zhoupi', 181088, 'smertina@a8.net', 'CpHo4JRlq');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (12, 'Tadeas', 'Rennels', '8863', 'Dakota', 'Menghai', 492017, 'trennelsb@istockphoto.com', 'wgVf82aDC');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (13, 'Feodor', 'Kernermann', '93674', 'Karstens', 'Tukan', 852903, 'fkernermannc@disqus.com', 'SWQJXPM7Ag');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (14, 'Wadsworth', 'Scatchar', '4503', 'Oak Valley', 'Girihieum', 634139, 'wscatchard@economist.com', 'MhhrEC');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (15, 'Gabrielle', 'Kwiek', '5021', 'Transport', 'Taquile', 988281, 'gkwieke@arstechnica.com', 'WIHkBC1J9kWv');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (16, 'Richmond', 'Pimblott', '4', 'Talisman', 'Ducheng', 802493, 'rpimblottf@amazon.co.jp', 'kf82Cu1bD7');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (17, 'Alberik', 'Galtone', '47', 'Arkansas', 'Le Lamentin', 421659, 'agaltoneg@e-recht24.de', '3DiCYNMMD');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (18, 'Cacilie', 'Gerriessen', '821', 'Pankratz', 'Laveiras', 785517, 'cgerriessenh@youtu.be', 'ONcE64l1iH');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (19, 'Tabbi', 'O''Sullivan', '5956', 'Southridge', 'Sinop', 888060, 'tosullivani@stumbleupon.com', 'tcONFUnZXF');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (20, 'Lenore', 'Folshom', '8', 'Tony', 'Tatuí', 658205, 'lfolshomj@printfriendly.com', 'VuXYEb8tXAB');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (21, 'Padraic', 'Cogle', '64', 'Melvin', 'Cumming', 661872, 'pcoglek@topsy.com', 'EvyCfgFKse');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (22, 'Zolly', 'Malarkey', '9438', 'Acker', 'Svojat', 411467, 'zmalarkeyl@sakura.ne.jp', 'AnUdJjrAN7');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (23, 'Judd', 'Langmead', '797', 'Browning', 'Courbevoie', 393126, 'jlangmeadm@timesonline.co.uk', 'YEZFQC9bONOH');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (24, 'Dex', 'Posnett', '4', 'Havey', 'Río Tercero', 996342, 'dposnettn@walmart.com', 'gx4V7GL');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (25, 'Jeralee', 'McGraffin', '1', 'Nelson', 'Gensi', 235624, 'jmcgraffino@psu.edu', 'fKenm2cCKwH5');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (26, 'Alley', 'Gorner', '78024', 'Pennsylvania', 'Fort-de-France', 516120, 'agornerp@redcross.org', 'EWnPxB');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (27, 'Rafe', 'Handyside', '29511', 'Old Shore', 'Nobeoka', 348756, 'rhandysideq@imgur.com', 'jceTSO');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (28, 'Reena', 'Riccioppo', '33882', 'Superior', 'Seoul', 933245, 'rriccioppor@flickr.com', '9Z32nhSHtuL');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (29, 'Jodie', 'Dunderdale', '7', 'Buell', 'Tosu', 784878, 'jdunderdales@simplemachines.org', 'QGOwj4XQ8xqF');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (30, 'Felita', 'Durno', '656', 'Shopko', 'Gwandu', 749587, 'fdurnot@icq.com', 'Mxrt3Yfp6VY');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (31, 'Joel', 'Jewson', '889', 'Anzinger', 'El Benque', 722249, 'jjewsonu@state.gov', '0wnexwJsAv');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (32, 'Henderson', 'Choppen', '46919', 'Montana', 'Bhola', 256803, 'hchoppenv@usgs.gov', 'b8JQyr');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (33, 'Odelia', 'Di Maria', '7141', 'Mitchell', 'Bilo', 355193, 'odimariaw@cdbaby.com', 'v4kprbjWShKD');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (34, 'Otha', 'Petrecz', '7', 'Thackeray', 'Staraya Toropa', 288586, 'opetreczx@bravesites.com', 'yRJbQolb');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (35, 'Earl', 'Side', '8', 'Del Mar', 'Changping', 915489, 'esidey@hp.com', 'VFIv5CCBl');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (36, 'Casie', 'Grichukhin', '87', 'Fallview', 'Kurjan', 823582, 'cgrichukhinz@cdbaby.com', 'mowIb8k41XVc');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (37, 'Demetri', 'Speechly', '990', 'Golf', 'Plato', 158783, 'dspeechly10@bluehost.com', 'gtiUH5uvDn');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (38, 'Ruby', 'Atkyns', '485', 'Anthes', 'Donghoufang', 269929, 'ratkyns11@howstuffworks.com', 'ZqcGa5VNKG6x');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (39, 'Jervis', 'Winfindine', '3062', 'Larry', 'Mae Ramat', 124823, 'jwinfindine12@dmoz.org', 'iceAecpqy7de');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (40, 'Cindra', 'Hapke', '1', 'Fordem', 'Yazykovo', 596481, 'chapke13@lulu.com', 'iJkM6x1oBR');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (41, 'Gaynor', 'Fernihough', '399', 'Loftsgordon', 'Socorro', 500461, 'gfernihough14@hao123.com', 'vTG49YIC1Vn');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (42, 'Roseann', 'Cosstick', '279', 'Fieldstone', 'Dengzhou', 574076, 'rcosstick15@amazon.de', 'IV3hU2WAD');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (43, 'Roberto', 'Pauluzzi', '46772', 'Del Sol', 'Kingersheim', 978567, 'rpauluzzi16@taobao.com', 'yGnqtDeYETkf');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (44, 'Kellia', 'Wolfendell', '22', 'Kedzie', 'Uhniv', 546114, 'kwolfendell17@ocn.ne.jp', 'PqYGvrA');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (45, 'Phineas', 'Vel', '82739', 'Sloan', 'Mossoró', 793548, 'pvel18@jalbum.net', 'tnQJcLi');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (46, 'Lawrence', 'Wainscoat', '017', 'Maywood', 'Palmeira das Missões', 289412, 'lwainscoat19@last.fm', '7I9MiqQskipQ');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (47, 'Ruddie', 'Ivashkov', '4', 'Summerview', 'Třešť', 496617, 'rivashkov1a@nsw.gov.au', 'sPzc3XgAC');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (48, 'Con', 'Rentoll', '6', 'Kropf', 'Wangfu', 779298, 'crentoll1b@reverbnation.com', 'poTRTk');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (49, 'Bill', 'Rattery', '4618', 'Welch', 'Bác Ái', 516646, 'brattery1c@mapy.cz', 'FWmuWOu');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (50, 'Nanette', 'Mahomet', '83033', 'Heath', 'Amuñgan', 146891, 'nmahomet1d@usa.gov', 'KahdGEG');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (51, 'Correna', 'Northcott', '9736', 'Arrowood', 'Monteiro', 898761, 'cnorthcott1e@omniture.com', 'nXpVHgs');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (52, 'Blondelle', 'Tomadoni', '37284', 'Eastwood', 'Trollhättan', 292747, 'btomadoni1f@globo.com', 'n5ZIeU');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (53, 'Wildon', 'McMylor', '647', 'Donald', 'Tsagaanchuluut', 461551, 'wmcmylor1g@yahoo.co.jp', 'ruTdgV6uNB7');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (54, 'Clywd', 'Capstake', '4574', 'Ridge Oak', 'Sharkawshchyna', 350734, 'ccapstake1h@wikimedia.org', 'MorGhJ');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (55, 'Zacharias', 'Adair', '7', 'Washington', 'Porsgrunn', 619140, 'zadair1i@shop-pro.jp', 'r8nqcFT');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (56, 'Munroe', 'Tucsell', '2062', 'Kennedy', 'Sedlice', 111241, 'mtucsell1j@addtoany.com', 'pMIB7l');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (57, 'Neville', 'Jemison', '4', 'New Castle', 'Yuannan', 101129, 'njemison1k@cbc.ca', 'qm3UUbgHQ');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (58, 'Sherye', 'Hallatt', '9070', 'Garrison', 'Zhoukoudian', 181954, 'shallatt1l@bravesites.com', 'OjTiRF2bMlXw');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (59, 'Siffre', 'Christophersen', '2', 'Pearson', 'Banjar Tegal Belodan', 567655, 'schristophersen1m@mit.edu', 'aVcGtG8rKFa');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (60, 'Carol-jean', 'Spurryer', '08423', 'Toban', 'Donetsk', 683752, 'cspurryer1n@gnu.org', 'AI8Bm7n');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (61, 'Nefen', 'Biskup', '67310', 'Eggendart', 'Banjar Batuaji Kaja', 511481, 'nbiskup1o@microsoft.com', 'ciiU0ZniwO');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (62, 'Morty', 'Guillon', '3', 'Schmedeman', 'Parachinar', 957677, 'mguillon1p@reuters.com', 'gObqXR');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (63, 'Earlie', 'Chattaway', '07', '1st', 'Luofang', 105938, 'echattaway1q@mayoclinic.com', '8cgC9ewWYKr');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (64, 'Leeann', 'Spight', '95', 'Florence', 'Marapat', 626224, 'lspight1r@com.com', 'R6Zr4jfg5kl');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (65, 'Jory', 'Burgiss', '7961', 'Dorton', 'Jimsar', 529984, 'jburgiss1s@stanford.edu', 'tSGe5j7qT9p');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (66, 'Jacky', 'Greenroad', '13387', 'Hoard', 'Huadi', 144446, 'jgreenroad1t@dion.ne.jp', 'Waa7rQSD');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (67, 'Sada', 'Kynton', '37', 'American', 'Socos', 743868, 'skynton1u@elpais.com', 'CbrbVOvo8aJ');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (68, 'Casie', 'Galvan', '976', 'Fieldstone', 'Orlando', 864940, 'cgalvan1v@ocn.ne.jp', 'MmGAwOo0');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (69, 'Burch', 'Camock', '368', 'Badeau', 'Turnišče', 527190, 'bcamock1w@umn.edu', '93k2T3T');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (70, 'Jobye', 'Louedey', '9843', 'Eliot', 'Varginha', 275791, 'jlouedey1x@infoseek.co.jp', 'tiG2Nw2');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (71, 'Chris', 'Newlove', '29', 'Morningstar', 'Sokyryany', 349060, 'cnewlove1y@arizona.edu', 'rwHmvs85He8');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (72, 'Merv', 'Gabbitis', '0', 'Springs', 'Žulová', 982135, 'mgabbitis1z@vistaprint.com', 'NjU8fuHxw2d');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (73, 'Artair', 'Tuma', '050', 'Northfield', 'Ivanteyevka', 358049, 'atuma20@kickstarter.com', 'A99sqMfIT');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (74, 'Ransell', 'Kleuer', '1', 'Fuller', 'Paty do Alferes', 153669, 'rkleuer21@booking.com', 'CG5FkHO');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (75, 'Vincents', 'Searby', '244', 'Crest Line', 'Campo Maior', 538432, 'vsearby22@list-manage.com', 'MwHR7bn7sa69');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (76, 'Caterina', 'Stanbury', '31', 'Farmco', 'Taipingxu', 979496, 'cstanbury23@jiathis.com', 'DTZRCjbnPkF');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (77, 'Berthe', 'Rego', '00797', 'Summerview', 'Semarapura', 304521, 'brego24@abc.net.au', 'hxFuV4CYZ');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (78, 'Gothart', 'Sketch', '2', 'Magdeline', 'Qianxu Zhen', 246951, 'gsketch25@cafepress.com', 'iWhAxxtBA');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (79, 'Owen', 'Venny', '84', 'Sutteridge', 'Jadów', 803458, 'ovenny26@jigsy.com', 'LqvVCbt');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (80, 'Dene', 'McNysche', '67', 'Schurz', 'Lodja', 933118, 'dmcnysche27@aol.com', 'nygXhUL');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (81, 'Franzen', 'Rubenczyk', '300', 'Maryland', 'Elói Mendes', 422734, 'frubenczyk28@twitter.com', 'oXvW0uF7');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (82, 'Estelle', 'Smedley', '14277', 'Di Loreto', 'Sinajana Village', 504227, 'esmedley29@npr.org', 'N67Uu0UIek');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (83, 'Dani', 'Boij', '06', 'Randy', 'Negla', 546903, 'dboij2a@discuz.net', 'JcoxcL');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (84, 'Pancho', 'Meegan', '5', 'Lotheville', 'Lizhai', 667428, 'pmeegan2b@baidu.com', 'gQb207E');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (85, 'Camile', 'Fincham', '0', 'Magdeline', 'Tsuyama', 669930, 'cfincham2c@stanford.edu', 'ZxH5f75flrd');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (86, 'Tanner', 'Niesel', '078', 'Haas', 'Dahuaishu', 439089, 'tniesel2d@naver.com', 'oBMEba7');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (87, 'Sidonnie', 'Poore', '09350', 'Victoria', 'Portorož', 554343, 'spoore2e@storify.com', 'kZOl7k9p1iA');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (88, 'Xever', 'Rijkeseis', '452', 'Becker', 'San Andres', 661761, 'xrijkeseis2f@edublogs.org', '9hJ8pkxIL6C');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (89, 'Northrop', 'Milbank', '06052', 'Namekagon', 'Megati Kelod', 290346, 'nmilbank2g@parallels.com', 'G0GqWm');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (90, 'Irena', 'Katzmann', '04', 'Jackson', 'Pining', 200541, 'ikatzmann2h@vimeo.com', 'trFZxj664LG');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (91, 'Augie', 'Follos', '64009', 'Warrior', 'Chuqui Chuqui', 667760, 'afollos2i@skype.com', 'YFQ7Fn');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (92, 'Patricio', 'Penni', '219', 'Vahlen', 'Puerto Barrios', 108936, 'ppenni2j@purevolume.com', '5e7gmRn65');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (93, 'Kerry', 'Wellstood', '97', 'Quincy', 'Bongandanga', 505818, 'kwellstood2k@wisc.edu', 'uQI3YGM3k2');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (94, 'Bartlett', 'McKerley', '3', 'Tony', 'Sankoutang', 906838, 'bmckerley2l@imgur.com', 'soJghorq8v');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (95, 'Janot', 'Iacopetti', '2928', 'Lunder', 'Nayak', 827349, 'jiacopetti2m@opera.com', 'CGfdkHTwvhnT');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (96, 'Hayward', 'Haeslier', '6941', 'Maple Wood', 'San Juan', 328237, 'hhaeslier2n@reverbnation.com', 'ZGpBTJ');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (97, 'Iolande', 'Windibank', '85564', 'Little Fleur', 'Farriar', 533423, 'iwindibank2o@imageshack.us', 'fPOKvZ1Xc');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (98, 'Cassondra', 'Raycroft', '6', 'Mallard', 'Novo', 681832, 'craycroft2p@usatoday.com', 'Fy1GMxdci');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (99, 'Minnaminnie', 'Pietrzak', '512', 'David', 'Stony Hill', 413768, 'mpietrzak2q@sohu.com', 'p9BXgU1qGcP8');
insert into Customer (Customer_ID, first_name, last_name, House_number, Locality, City, Pincode, email_address, password) values (100, 'Maegan', 'Ranfield', '50839', '4th', 'Pragen Selatan', 482296, 'mranfield2r@discovery.com', 'Cw8rOq0LnB');


select * from customer;
# Vendor
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (1, 'Otes', 'Renwick', '34373', 'Palaióchora', 803147);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (2, 'Junette', 'Barnhart', '40094', 'Muara Siberut', 827734);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (3, 'Allissa', 'Biggerstaff', '8999', 'Victoria', 778846);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (4, 'Madelaine', 'Kissick', '320', 'Zhangxi', 709932);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (5, 'Mallorie', 'Tutill', '92284', 'Oslo', 776945);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (6, 'Juliane', 'O''Finan', '481', 'Cruzeiro', 123220);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (7, 'Lynnell', 'Devlin', '37765', 'Guaratinguetá', 174234);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (8, 'Shanta', 'Greg', '136', 'Lākshām', 428485);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (9, 'Alic', 'Sywell', '4061', 'Suphan Buri', 619089);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (10, 'Joyann', 'Pidwell', '2', 'Baidoa', 904749);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (11, 'Kimble', 'McAlarney', '64100', 'Mjamaoué', 855149);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (12, 'Minnaminnie', 'Yonge', '182', 'Pasar', 925203);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (13, 'Raviv', 'Eyer', '4', 'Bao’an', 852404);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (14, 'Janek', 'Gossage', '525', 'Cumming', 659351);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (15, 'Dicky', 'Hrihorovich', '31607', 'Gävle', 252198);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (16, 'Yevette', 'Antoszczyk', '65', 'Strömsund', 453380);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (17, 'Merle', 'Wenzel', '8', 'Waipawa', 716951);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (18, 'Shellysheldon', 'Baunton', '849', 'Nogueira da Regedoura', 958339);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (19, 'Tad', 'Longthorn', '73', 'Eisen', 159310);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (20, 'Seka', 'Arnolds', '589', 'Batroûn', 769079);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (21, 'Eirena', 'Downe', '55728', 'Witzenhausen', 147505);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (22, 'Cassie', 'Novic', '8', 'Kodinsk', 790770);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (23, 'Enos', 'Dicks', '2191', 'Kanaya', 510648);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (24, 'Adriaens', 'Izhakov', '2183', 'Songjianghe', 983827);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (25, 'Milton', 'Nenci', '00', 'Sapadun', 293425);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (26, 'Hadley', 'Eaton', '8', 'Terny', 440236);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (27, 'Kelcie', 'Esche', '29', 'Kushchëvskaya', 961581);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (28, 'Gertrudis', 'O''Nion', '4', 'Denver', 304206);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (29, 'Paul', 'Dewen', '73141', 'Flandes', 671437);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (30, 'Nat', 'Kiledal', '3883', 'Huanipaca', 338829);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (31, 'Cathee', 'Rawood', '14', 'Zhigong', 310214);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (32, 'Deedee', 'Sneesbie', '927', 'Saurimo', 749022);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (33, 'Edin', 'Daens', '005', 'Padabeunghar', 628261);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (34, 'Berna', 'Bick', '4515', 'Tierimu', 431115);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (35, 'Cassandre', 'Kestin', '2137', 'Karangsembung', 734995);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (36, 'Elsie', 'Bruhnsen', '74821', 'Imotski', 239496);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (37, 'Velma', 'Gaveltone', '62', 'Teplice', 281832);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (38, 'Markos', 'Ratledge', '3', 'Santa Maria Oliveira', 183821);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (39, 'Wendy', 'Oxenden', '54', 'Xiaomenjia', 740904);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (40, 'Howard', 'Harmar', '1', 'Guiping', 285613);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (41, 'Poppy', 'Everest', '747', 'Songshan', 332522);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (42, 'Kristi', 'de Marco', '7', 'Luftinjë', 716283);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (43, 'Juieta', 'Thomasson', '35171', 'Akim Swedru', 940662);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (44, 'Garret', 'Toffanini', '84', 'Jurh', 835933);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (45, 'Dewey', 'Camous', '61702', 'Káto Dhiminió', 772053);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (46, 'Thorsten', 'Fabry', '568', 'Borlänge', 722698);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (47, 'Ari', 'Russi', '89', 'Bohus', 837786);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (48, 'Maggi', 'Kreutzer', '53464', 'Seren Barat', 554170);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (49, 'Milt', 'Sille', '38', 'Petaling Jaya', 586716);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (50, 'Sela', 'Sickert', '9023', 'Helmsange', 131330);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (51, 'Cherish', 'Buglar', '1803', 'Yazman', 931293);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (52, 'Deb', 'LAbbet', '4', 'Khvatovka', 206137);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (53, 'Tymothy', 'Jee', '51', 'Dahuangwei', 754789);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (54, 'Emyle', 'Vaugham', '0650', 'Krasne', 502275);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (55, 'Kean', 'Hackford', '468', 'Pervoural’sk', 508980);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (56, 'Vittorio', 'Bellchamber', '8141', 'Нераште', 986257);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (57, 'Tandi', 'Whitney', '279', 'Ganzhou', 145550);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (58, 'Lonnard', 'Mifflin', '70', 'Qixian', 915567);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (59, 'Gertrude', 'Sate', '51765', 'Baiqi', 793648);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (60, 'Delmer', 'Costar', '4475', 'Bells Corners', 725064);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (61, 'Jayme', 'Donnersberg', '76', 'Gorna Oryakhovitsa', 617541);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (62, 'Ruperta', 'MacArthur', '64', 'Linhó', 332952);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (63, 'Erena', 'Luquet', '11648', 'Huilongshan', 828273);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (64, 'Haroun', 'Rowbottam', '1', 'Guanbuqiao', 664844);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (65, 'Marga', 'Bestar', '8913', 'Hullo', 686310);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (66, 'Neila', 'Pendleton', '88', 'Bang Pa-in', 767257);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (67, 'Thomasin', 'Moy', '29607', 'Namballe', 620429);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (68, 'Helsa', 'Harrema', '8', 'Sehwān', 530051);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (69, 'Amandie', 'Leschelle', '3', 'La Serena', 546575);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (70, 'Mora', 'Cosford', '9', 'Stockholm', 710499);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (71, 'Dolph', 'Hammerberg', '68933', 'Hidalgo', 886983);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (72, 'Neron', 'Pfaffel', '833', 'Krrabë', 835398);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (73, 'Licha', 'Woolis', '18', 'Nawal', 296592);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (74, 'Sophey', 'Alesi', '2', 'Stockholm', 394287);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (75, 'Ernie', 'Rapport', '72113', 'Qionghai', 491503);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (76, 'Michele', 'Botham', '464', 'Zorgo', 713449);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (77, 'Mattie', 'Turn', '191', 'Lianzhou', 576732);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (78, 'Earl', 'Urridge', '878', 'Covão da Carvalha', 185403);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (79, 'Reg', 'Gumm', '36210', 'Banī Khaddāsh', 891442);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (80, 'Nance', 'Lamey', '9', 'Polanka Wielka', 598674);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (81, 'Tate', 'Phifer', '64659', 'Novi Beograd', 521118);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (82, 'Barr', 'Sture', '14528', 'Malabonot', 153543);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (83, 'Camella', 'Seares', '10669', 'Novoukrainskiy', 363179);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (84, 'Naoma', 'Urey', '352', 'Xing’an', 492191);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (85, 'Merla', 'Sirette', '4143', 'Charlotte', 169462);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (86, 'Katlin', 'Antoni', '5', 'Karabanovo', 470308);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (87, 'Sonya', 'Jeavon', '79934', 'Säter', 591669);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (88, 'Carly', 'Le Leu', '451', 'Lacdayan', 966123);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (89, 'Larina', 'Pettitt', '96', 'Gengqing', 515689);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (90, 'Cortney', 'Lehr', '03', 'Solana', 412671);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (91, 'Shell', 'Venneur', '12', 'Walakeri', 656366);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (92, 'Truman', 'Glantz', '96945', 'Iporá', 334829);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (93, 'Nichole', 'Maghull', '5', 'Hämeenkoski', 545143);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (94, 'Natasha', 'Eim', '4', 'Nova Pazova', 318782);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (95, 'Ammamaria', 'Grutchfield', '5', 'Blizne', 308615);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (96, 'Kameko', 'Ferrara', '46', 'San Jacinto', 651094);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (97, 'Federico', 'Rickards', '6866', 'Bābol', 353101);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (98, 'Baily', 'Lamp', '2719', 'Damatulan', 403162);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (99, 'Nadia', 'Threadgall', '192', 'Río de Oro', 999530);
insert into Vendor (Vendor_id, first_name, last_name, Plot_number, City, Pincode) values (100, 'Anders', 'Garlette', '0', 'Vinsady', 540491);
# Rows:


# Warehouse
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (1, 99, 'San Quintin', 793623);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (2, 20, 'Hampton', 991302);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (3, 86, 'Unidos', 556905);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (4, 29, 'Stockholm', 196614);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (5, 67, 'Omaha', 821660);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (6, 51, 'Rio Negrinho', 597713);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (7, 79, 'Maisons-Laffitte', 990051);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (8, 19, 'Otaru', 594721);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (9, 64, 'Lenchwe Le Tau', 756360);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (10, 32, 'Chamouny', 241950);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (11, 83, 'Lampang', 379701);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (12, 36, 'La Tebaida', 722475);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (13, 74, 'Tlumačov', 846504);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (14, 86, 'Tucuran', 651424);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (15, 32, 'Placer', 113562);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (16, 27, 'Santa Marcela', 345777);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (17, 45, 'George Town', 438626);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (18, 17, 'Graksop', 498496);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (19, 18, 'Powidz', 436050);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (20, 84, 'Vinhais', 359658);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (21, 57, 'Katrineholm', 817172);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (22, 75, 'Colonia Mauricio José Troche', 210387);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (23, 78, 'Tadianjie', 463697);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (24, 51, 'Tynne', 750703);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (25, 36, 'Salacgrīva', 823910);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (26, 86, 'Himeji', 136055);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (27, 58, 'Shigu', 915216);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (28, 10, 'Ampasimanolotra', 988569);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (29, 23, 'Tsimasham', 511016);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (30, 47, 'Semerak', 606529);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (31, 82, 'Cayur', 441191);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (32, 16, 'La Quebrada', 869431);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (33, 36, 'Ciyun', 568380);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (34, 9, 'Uenohara', 454934);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (35, 58, 'Iset', 219598);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (36, 5, 'Busan', 113816);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (37, 36, 'Kebonkalapa', 280701);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (38, 8, 'Praia', 919880);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (39, 28, 'Czerniewice', 459558);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (40, 67, 'Raciążek', 342776);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (41, 47, 'Saint-Étienne', 641090);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (42, 87, 'Ailibugai', 246135);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (43, 11, 'Santo Amaro', 244027);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (44, 79, 'Yanglinqiao', 410929);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (45, 99, 'Boyu', 333246);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (46, 67, 'Aki', 333552);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (47, 68, 'Murganhal', 380507);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (48, 3, 'Puan Selatan', 460305);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (49, 21, 'La Virginia', 535373);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (50, 21, 'Tampocon', 325661);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (51, 100, 'Ubon Ratchathani', 424534);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (52, 90, 'Yankou', 298697);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (53, 56, 'Santiago', 978239);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (54, 21, 'Tromsø', 637399);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (55, 21, 'Petrodvorets', 359887);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (56, 57, 'Yongchang', 614589);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (57, 60, 'Nanyang', 593341);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (58, 4, 'Bené Beraq', 875929);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (59, 91, 'Estribeiro', 181776);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (60, 11, 'Ojos de Agua', 502392);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (61, 47, 'Kampánis', 670161);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (62, 50, 'San Andres', 635996);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (63, 22, 'Kálamos', 669100);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (64, 16, 'Vilar', 439804);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (65, 33, 'Cumedak', 894974);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (66, 66, 'Aioi', 930218);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (67, 19, 'Ożarów', 369477);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (68, 77, 'Szolnok', 834440);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (69, 81, 'Jinta', 369614);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (70, 48, 'Ust-Kamenogorsk', 712337);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (71, 61, 'Tandzut', 968749);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (72, 23, 'Itapetininga', 775810);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (73, 35, 'Marseille', 590137);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (74, 50, 'Dzikowiec', 713814);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (75, 38, 'Lyubertsy', 440726);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (76, 58, 'Pasirputih', 602476);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (77, 74, 'Bulog', 821563);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (78, 7, 'Dimitrov', 694818);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (79, 44, 'Wanglu Kulon', 784623);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (80, 43, 'Tyler', 486484);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (81, 88, 'Budrus', 782139);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (82, 64, 'Ugljan', 597611);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (83, 57, 'Flushing', 193185);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (84, 11, 'Careva Ćuprija', 811734);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (85, 4, 'Lashma', 195053);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (86, 23, 'Ar Rujum', 717019);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (87, 37, 'Rouen', 216679);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (88, 76, 'Zhaoxiang', 689073);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (89, 8, 'Port-Vila', 964279);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (90, 26, 'Pinheiral', 327832);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (91, 45, 'Ushi', 633992);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (92, 9, 'Barão de Melgaço', 212160);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (93, 16, 'Rio Brilhante', 497891);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (94, 75, 'Trà Ôn', 276014);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (95, 49, 'Manokwari', 339807);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (96, 11, 'Amiens', 177493);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (97, 33, 'Houmt Souk', 815458);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (98, 72, 'Nantang', 314909);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (99, 11, 'Pangani', 906523);
insert into Warehouse (Warehouse_ID, Plot_number, City, pincode) values (100, 18, 'Nogent-sur-Marne', 583701);



#Orders





insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (1, 62089.49, 27.65, 9.13);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (2, 23387.82, 8.85, 24.41);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (3, 63751.88, 24.84, 6.42);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (4, 99487.9, 16.38, 18.82);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (5, 9520.38, 14.08, 7.94);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (6, 21205.05, 9.0, 10.3);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (7, 23811.41, 20.66, 13.95);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (8, 90866.35, 10.86, 18.89);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (9, 44023.32, 14.33, 7.83);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (10, 40075.63, 11.44, 21.78);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (11, 87547.27, 29.9, 17.12);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (12, 72935.72, 21.99, 27.74);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (13, 33007.6, 29.53, 7.67);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (14, 2704.33, 15.46, 28.27);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (15, 73452.45, 10.66, 8.11);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (16, 31590.77, 7.51, 10.46);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (17, 72144.71, 15.05, 25.22);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (18, 35129.39, 8.41, 16.09);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (19, 23374.42, 11.39, 14.89);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (20, 28473.57, 16.84, 5.4);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (21, 68324.26, 7.8, 29.89);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (22, 8254.45, 29.05, 19.0);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (23, 85859.17, 9.47, 28.57);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (24, 14168.52, 24.9, 23.71);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (25, 68352.13, 19.02, 3.36);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (26, 6533.48, 22.33, 4.52);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (27, 5320.18, 14.48, 0.64);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (28, 69121.93, 14.86, 6.63);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (29, 15884.33, 15.12, 11.19);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (30, 61956.41, 22.28, 17.52);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (31, 38021.82, 6.63, 14.94);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (32, 64359.2, 18.02, 5.96);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (33, 37225.47, 15.84, 26.16);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (34, 36613.01, 6.08, 29.51);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (35, 62902.54, 17.73, 15.1);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (36, 16129.0, 11.35, 26.46);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (37, 80768.74, 16.48, 21.18);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (38, 30886.05, 19.32, 17.29);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (39, 48429.05, 18.79, 15.3);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (40, 78696.04, 13.52, 24.69);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (41, 30848.25, 28.0, 20.74);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (42, 19637.06, 6.31, 17.48);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (43, 35763.1, 18.76, 17.96);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (44, 5398.04, 21.99, 20.82);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (45, 79465.05, 9.71, 23.07);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (46, 94433.35, 29.47, 15.36);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (47, 77875.17, 24.13, 17.3);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (48, 6996.77, 11.28, 14.71);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (49, 9614.46, 6.84, 10.73);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (50, 74700.23, 15.59, 7.19);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (51, 62368.71, 16.7, 2.13);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (52, 15326.77, 22.99, 21.35);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (53, 97063.68, 22.58, 16.42);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (54, 45147.18, 14.99, 25.75);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (55, 19491.6, 10.61, 4.76);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (56, 15640.28, 22.2, 7.82);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (57, 35114.84, 23.39, 2.8);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (58, 35756.84, 20.16, 11.31);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (59, 45799.9, 10.2, 14.81);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (60, 3599.64, 8.96, 18.42);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (61, 78618.23, 8.16, 14.29);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (62, 39739.67, 14.23, 25.31);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (63, 1534.48, 11.85, 24.11);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (64, 22578.46, 29.11, 8.73);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (65, 3132.25, 9.2, 19.08);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (66, 80018.86, 23.11, 18.2);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (67, 14471.01, 22.92, 10.54);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (68, 77727.55, 10.96, 10.25);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (69, 21010.74, 25.63, 26.37);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (70, 70143.37, 18.58, 12.74);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (71, 17195.0, 14.23, 1.44);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (72, 43192.46, 10.16, 9.61);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (73, 62602.15, 19.14, 19.14);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (74, 51097.32, 11.09, 8.21);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (75, 2837.48, 6.36, 4.74);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (76, 8997.54, 23.94, 8.47);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (77, 1422.83, 27.71, 9.62);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (78, 73068.32, 12.11, 12.45);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (79, 75930.29, 17.68, 11.07);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (80, 87280.71, 18.17, 25.01);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (81, 14918.51, 22.38, 15.4);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (82, 38502.47, 25.09, 11.29);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (83, 22503.23, 19.63, 12.11);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (84, 21321.16, 12.9, 25.44);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (85, 34327.68, 17.13, 9.22);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (86, 8573.57, 6.48, 13.48);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (87, 91631.07, 5.1, 6.69);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (88, 32275.62, 19.3, 13.75);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (89, 7969.12, 12.67, 18.19);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (90, 30211.32, 25.86, 20.81);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (91, 23177.86, 24.9, 22.59);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (92, 93802.95, 20.92, 5.67);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (93, 23549.92, 24.08, 8.16);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (94, 52759.13, 24.61, 6.39);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (95, 68512.39, 29.33, 2.75);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (96, 4251.08, 20.25, 17.11);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (97, 309.41, 22.84, 21.78);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (98, 4686.67, 20.76, 18.25);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (99, 99778.52, 13.32, 12.4);
insert into Orders (Order_id, Total_price, Taxes, Total_Discount_Percentage) values (100, 24184.44, 27.87, 5.04);
